import './People.css'
import About_P from '../About_P/About_P'

export default function People() {
  return (
    <div className="People">
        <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567095274716-O0BGWEH4GPBQJRXSZYWL/morris.jpg?format=1500w'} Pname={'JIM MORRIS'} job={'PRESIDENT'} 
        about={`Jim Morris is President of Pixar Animation Studios, where he oversees all of the company’s productions and operations.  Morris began working at Pixar in 2005.  Films under his supervision include “Ratatouille,” “Up,” “Toy Story 3,” “Cars 2,” “Brave,” “Monsters University,” “Inside Out,” “The Good Dinosaur,” “Finding Dory,” “Cars 3,” “Coco” and “Incredibles 2.” As a producer, Morris most recently made the live-action Disney feature “John Carter” with director Andrew Stanton. He also produced Pixar’s “WALL•E,” which won the Academy Award® for Best Animated Feature. Morris was also awarded Producer of the Year in Animated Theatrical Motion Pictures from the Producer’s Guild of America, the AFI Award, the Golden Globe and the Visual Effects Society Best Animated Feature Award for “WALL•E.”

        Prior to joining Pixar, Morris held a range of key positions for 17 years in various divisions of Lucasfilm Ltd.  He served as President of Lucas Digital Ltd., and managed its three divisions, Industrial Light & Magic (ILM), Skywalker Sound and Lucasfilm Animation. As ILM’s General Manager for more than 13 years, he supervised a staff of over 1,400 artists and technicians, and guided the largest visual effects facility in the entertainment industry.  
        
        With Morris’ oversight, ILM created the groundbreaking and Academy Award®-winning visual effects in “Jurassic Park,” “Death Becomes Her,” “Terminator 2” and “Forrest Gump.” Other notable projects completed under his management include “Mission: Impossible,” “Twister,” “Saving Private Ryan,” “Star Wars: Episodes I,” “Star Wars: Episode II,” “The Perfect Storm,” “Pearl Harbor,” “Minority Report,” “Pirates of the Caribbean,” “Master and Commander,” and three films in the “Harry Potter” series.
        
        Morris joined ILM in 1987 as a Producer of visual effects for films and commercials. Among Morris’ producing credits are James Cameron’s “The Abyss” (which earned the Academy Award® for Best Achievement in Visual Effects), and Steven Spielberg’s “Always.”
        
        Before joining ILM, Morris was Executive Producer at Arnold & Associates, where he oversaw the company’s three offices and produced commercials for clients such as Atari, Chevron and Mattel.  Prior to that, Morris was Executive Producer at One Pass, where he headed the commercial production division. He also served in the production departments at advertising agencies J. Walter Thompson, and Foote, Cone & Belding in San Francisco.  Morris worked as a producer and director for PBS, and began his career as a cameraman and editor at NBC
        
        Morris is the recipient of the Producers Guild Digital 50 Award, the Visual Effects Society Board of Directors Award and the Visual Effects Society Founders Award.  He has also been named a VES Fellow.  Morris served for many years as President of the San Francisco Film Commission, and is Founding Chair of the VES.  He is a member of AMPAS, PGA, BAFTA, VES and ASIFA, and currently serves as a member of Motion Picture Academy’s Finance Committee.  Morris earned a Bachelor of Science degree in Film and a Master of Science degree in Television/Radio from the Newhouse School at Syracuse University.  `}
        /> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567526767838-LLSNIFSI4A8PI2I5J864/docter2.jpg?format=1500w'} Pname={'PETE DOCTER'} job={'CHIEF CREATIVE OFFICER'}
        about={`Pete Docter is the Oscar®-winning director of “Monsters, Inc.,” “Up,” and "Inside Out," and Chief Creative Officer at Pixar Animation Studios. He most recently directed Disney and Pixar’s Oscar®-winning feature film “Soul” with producer Dana Murray and co-director Kemp Powers, which is now streaming on Disney+.  

        Starting at Pixar in 1990 as the studio’s third animator, Docter collaborated and help develop the story and characters for “Toy Story,” Pixar’s first full-length animated feature film, for which he also was supervising animator.  He served as a storyboard artist on “A Bug’s Life,” and wrote initial story treatments for both “Toy Story 2” and “WALL•E.” Aside from directing his three films, Docter also executive produced "Monsters University" and the Academy Award®-winning “Brave.”
        
        Docter’s interest in animation began at the age of eight when he created his first flipbook.  He studied character animation at California Institute of the Arts (CalArts) in Valencia, California, where he produced a variety of short films, one of which won a Student Academy Award®.  Those films have since been shown in animation festivals worldwide and are featured on the "Pixar Short Films Collection Volume 2." Upon joining Pixar, he animated and directed several commercials, and has been nominated for eight Academy Awards® including Best Animated Feature-winners “Up” and "Inside Out" and nominee “Monsters, Inc.,” and Best Original Screenplay for “Up,” "Inside Out" and “WALL•E.” In 2010, "Up" also was nominated for a Best Picture Oscar by the Academy of Motion Picture Arts and Sciences. 
        
        `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1574793820678-J7FVEQ2ASS7LDPE3LA6M/rema2.jpg?format=1500w'} Pname={'REEMA BATNAGAR'} job={'VICE PRESIDENT, HUMAN RESOURCES '}
        about={`Reema Batnagar joined Pixar Animation Studios in February 2019 as Vice President, Human Resources. In her role, Batnagar is responsible for leading Pixar’s human resources department, which includes talent acquisition, leadership/organizational development, total rewards, and employee relations.

        Batnagar brings over 20 years of HR experience to the job. Prior to Pixar, Batnagar worked at Sony Interactive Entertainment as Head of HR for Sales & Marketing, where she led learning and development and talent management. She has also held a variety of senior HR leadership and organizational development roles at VMware, Adobe, and Intuit. 
       
        Growing up in St. Paul, Minnesota, Batnagar holds a bachelor’s degree in communications and psychology from St. Olaf College and a master’s degree in human resources and organizational development from University of Minnesota.`}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567096756104-81XMLW3DFOVL2PN22Y2G/lindsey.jpg?format=1500w'} Pname={'LINDSEY COLLINS'} job={'SENIOR VICE PRESIDENT/DEVELOPMENT'}
        about={`Lindsey Collins joined Pixar Animation Studios in May 1997. She has since worked in various capacities on a number of Pixar’s feature films. Collins’ film credits include “A Bug’s Life,” “Toy Story 2” and the Academy Award®-winning “Finding Nemo,” and “Ratatouille.” Collins also provided the voice of the character Mia in Pixar’s 2006 release, “Cars.”

        Collins co-produced the Golden Globe® and Oscar® winning feature “WALL•E” with producer Jim Morris and director Andrew Stanton and was a producer on the Walt Disney Studios feature “John Carter of Mars.” Collins was most recently the producer of Disney and Pixar’s “Finding Dory” in 2016. Collins has since taken on the role of Senior Vice President of Development, while she continues to produce.
        
        Prior to joining Pixar, Collins worked at Disney Feature Animation for three years, managing creative teams on the films “Pocahontas,” “The Hunchback of Notre Dame,” and “Hercules.”
        
        Collins earned a Bachelor of Arts in Diplomacy and World Affairs at Occidental College in Los Angeles. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/586e2c27-8605-4897-ba6e-b5a9b65332f7/20230110TylerFazakerley01.jpg?format=1500w'} Pname={'TYLER FAZAKERLEY '} job={'VICE PRESIDENT, SYSTEMS '}
        about={`Tyler Fazakerley joined Pixar Animation Studios in February of 2007, working as a Systems Administrator on multiple Pixar titles including Academy Award®-winning films “Ratatouille,” “WALL-E,” “Toy Story 3,” and “Brave.” Following his work on these films, he managed several Systems teams on features including “The Good Dinosaur,” “Finding Dory,” and “Incredibles 2,” in addition to Academy Award®-winning films “Inside Out” and “Coco.” Most recently Fazakerley worked as Director of Systems on Academy Award®-winning films “Toy Story 4” and “Soul,” in addition to “Onward” and Pixar’s upcoming feature film “Luca,” releasing on June 18, 2021 on Disney+.

        Currently in his role as Vice President of Systems, Fazakerley oversees Studio technology including data centers, high-performance computing systems, theaters, recording studios, editorial systems, workstations, teleconferencing, and production pipeline software engineering.
        
        Prior to Pixar, Fazakerley operated a technology consulting business in the San Francisco Bay Area. Earlier in his career he was a part of Apple’s early retail effort, opening the first store to serve the San Francisco and East Bay Area markets. 
        
        Fazakerley grew up in the Washington D.C. and Massachusetts areas. He studied in Oxford before moving to Boston, MA to attend Emerson College. 
        
        He currently resides in Oakland, CA. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1568849287238-U0B8Q14384PRRS28F5X6/garson4.jpg?format=1500w'} Pname={'JONATHAN GARSON'} job={'SENIOR VICE PRESIDENT,WORLDWIDE MARKETING & FRANCHISE'}
        about={`Jonathan Garson is the Senior Vice President of Worldwide Marketing and Franchise for Pixar Animation Studios.  In this role, he oversees all marketing and franchise efforts for the Studio, including long-lead planning, marketing and campaign development.  Garson is also responsible for managing the Studio’s promotional, creative content, consumer products, theme parks, archives, exhibition and creative services departments.

        Prior to joining Pixar in 2010, Garson served as the Vice President of Franchise and Product Management at The Walt Disney Studios (TWDS), where was responsible for working with various divisions of the Walt Disney Company to manage long-term strategic franchise planning and identify growth opportunities for the Studio’s animated properties. During his 16-year tenure at TWDS, Garson began as an assistant to chairman of The Walt Disney Studios, and was subsequently promoted to administrator of national promotions. In September 2000, Jonathan transitioned into a new role as director of marketing, synergy and special projects for TWDS, and in April 2002, was promoted to Vice President of broadcast publicity for Buena Vista Pictures Marketing, where he developed and executed feature film broadcast and integrated marketing strategies throughout TWDS and other third-party broadcast outlets. In May 2004, Michael Eisner and Bob Iger appointed Jonathan to the position of vice president, corporate synergy and special projects for The Walt Disney Company. In that role, Jonathan was primarily responsible for conceptualizing and developing plans and strategies to foster collaboration across all business units in an effort to drive overall growth for the company.  
        
        Born and raised in Southern California, Garson earned a Bachelor of Arts in business from Arizona State University and a Master’s in Business Administration from California State University, Northridge. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1623777042143-9P3KYZV7Y33QOB6A9I5C/joseph.jpg?format=1500w'} Pname={'MARK JOSEPH'} job={'VICE PRESIDENT, CONTROLLER & FACILITY OPERATIONS'}
        about={`Mark Joseph joined Pixar Animation Studios in 2004 as the Director of Accounting and Reporting. Following Disney’s acquisition of Pixar in 2006, he was promoted to Controller and played a key role in transitioning Pixar from a public company to a wholly owned subsidiary. In 2011, Joseph was promoted to Vice President, Controller and Facility Operations. His current responsibilities include oversight of Corporate Accounting and Tax, LTI and Stock Administration, Facilities Operations, Café and the Studio Store.

        Joseph brings to Pixar over 25 years of accounting and finance experience. Prior to Pixar, he held various Controller and Assistant Controller roles at publicly held telecom, software and manufacturing companies between 1997 and 2004. He began his career at PricewaterhouseCoopers LLP after graduating from California Polytechnic State University in 1993 with a B.S. in Business Administration. Joseph is a Certified Public Accountant, State of California.    `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1623777290396-J0QBJ90CEWALPJTOXYKJ/kaiser.jpg?format=1500w'} Pname={'CHRIS KAISER'} job={'VICE PRESIDENT, FINANCE & STRATEGY '}
        about={`Chris Kaiser joined Pixar in January 2019.  As Vice President, Finance & Strategy, Kaiser oversees the Finance and Accounting functions, as well as the teams that manage and operate Pixar's Facilities, Security, Cafe, and Studio Store.

        Kaiser grew up in Crystal Lake, Illinois. He attended the U.S. Naval Academy before becoming a submarine officer in the United States Navy.  After his naval service, Kaiser attended Northwestern University and worked as a Strategy Consultant at the Boston Consulting Group.  He then joined The Walt Disney Company and held various finance roles over 15 years, including positions at Walt Disney World, Disney corporate, and Disneyland Paris.`}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1623777496366-9TTLEXZ15I70HQW9NS9S/kennedy.jpg?format=1500w'} Pname={'JAMES M. KENNEDY'} job={'SENIOR VICE PRESIDENT,BUSINESS AFFAIRS AND CHIEF LEGAL COUNSEL'}
        about={`Jim Kennedy joined Pixar in September 2009 as its Senior Vice President, Business Affairs and Chief Legal Counsel. In this position, he is responsible for overseeing Pixar’s Legal and Business Affairs matters, and coordinating with the Legal and Business Affairs groups at Walt Disney Studios.  Kennedy also serves a member of Pixar’s senior leadership team.

        Kennedy brings to Pixar over 35 years of legal and business affairs experience in entertainment-related companies.  Prior to joining Pixar, he served as Executive Vice President, Business & Legal Affairs and Corporate Secretary at THQ Inc., a publicly-held entertainment software company in Agoura Hills, CA.  He previously held executive legal and business affairs positions at companies such as Electronic Arts Inc., Mindscape Inc., Lucasfilm, Lucas Digital and LucasArts Entertainment Company.  He began his career as a corporate attorney in the Century City, CA office of Gibson Dunn & Crutcher.  Kennedy has also been a lecturer and adjunct professor at the undergraduate and law school level, and a frequent speaker and panelist at entertainment industry events at which free food and cocktails are served.  He holds an undergraduate degree from Princeton University, a law degree from Boston College School of Law, and an MBA in Strategic Leadership from Dominican University of California.`}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1623778895643-LEQ0E8J7I1YTJ6DTPDNX/may.jpg?format=1500w'} Pname={'STEVE MAY'} job={'VICE PRESIDENT, CHIEF TECHNOLOGY OFFICER'}
        about={`Steve May’s tenure at Pixar Animation Studios spans more than 20 years, where he is currently Vice President, Chief Technology Officer. In this role, May oversees all technology at the studio including software R&D, information systems, RenderMan, and the development of visual effects tools and processes for each film. 

        May began his tenure at Pixar Animation Studios in 1998 as a shading and modeling technical director on “Toy Story 2.” For Pixar’s next film “Monsters, Inc.,” May worked as the simulation and effects sequence supervisor and helped to pioneer the fur technology and overall look for the character Sullivan. He then went on to work on the Academy Award®-winning feature “Finding Nemo,” as the CG supervisor for the shark characters and Sydney Harbor environment. 
        
        May served at the effects supervisor on Golden Globe®-winner “Cars,” overseeing all of the film’s visual effects. His next role was as the supervising technical director for Academy Award®-winning feature film “Up.” During his tenure as CTO, May also served as supervising technical director for the final shot production of the Academy Award®-winning film “Brave.” 
        
        Born in Sarasota, Florida, May spent his childhood in Mansfield, Ohio. Fueled by a love of art and science (and an image in a magazine created in 1984 by a future Pixar colleague), May decided to pursue a career in computer animation. Before finding his way to Pixar, he was a member of the research faculty at The Ohio State University where he taught computer animation and computer graphics courses at the University’s College of the Arts and the College of Engineering. He received a Ph.D. in computer science as well as bachelor’s of science and master’s of science degrees from The Ohio State University. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1568908379677-NUF8RL34IRTI5KA76D9O/oliver.jpg?format=1500w'} Pname={'OLIVER MEISEBERG'} job={'VICE PRESIDENT, RENDERMAN '}
        about={`Oliver Meiseberg began at Pixar Animation Studios in July 2019 as Vice President, Renderman. The Renderman team develops Pixar’s leading rendering technology that helps artists to bring every pixel to the big screen. Meiseberg is responsible for managing the Renderman team, in addition to working on Pixar’s next generation software for upcoming films. Because Renderman sees a high adoption even beyond Pixar, the team also supports studios including Industrial Light and Magic, MPC, and other customers.

        Meiseberg was born in Blomberg, a small town in the northern part of Germany. He received a degree in Media Economics from FHM Bielefeld in Germany.  
        
        Prior to Pixar, Meiseberg worked in production before going to RTL Disney Television. He was also Chief Product Officer at Maxon and responsible for the development of Cinema 4D.
        
        Meiseberg currently resides in South Lake Union in downtown Seattle, WA. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567110044333-915Q1V8BJLFQP8T1JDNL/rivera_2.jpg?format=1500w'} Pname={'JONAS RIVERA'} job={'SENIOR VICE PRESIDENT, PRODUCTION'}
        about={`Jonas Rivera joined Pixar Animation Studios in 1994 to work on “Toy Story” as the studio’s first and only production intern at the time. He advanced roles on almost every subsequent Pixar feature film until becoming producer of the studio's 2009 film "Up." In 2015, Rivera teamed up again with director Pete Docter for “Inside Out,” which won an Academy Award® for best animated feature and was nominated for best original screenplay. His most recent role as producer was on Pixar’s feature film, “Toy Story 4,” which released in Summer, 2019. 

        Rivera's various past roles at the studio include art department coordinator for “A Bug’s Life,” marketing and creative resources coordinator on “Toy Story 2,” art department manager on “Monsters, Inc.,” and production manager on “Cars.”
        
        In his executive role as senior vice president, production, Rivera oversees all of feature film production at the studio. 
        
        Rivera has twice been awarded Producer of the Year in Animated Features by the Producers Guild of America for his work on "Up" and "Inside Out." "Up" earned a nomination for best picture by the Academy of Motion Picture Arts and Sciences—only the second animated film in history to do so. 
        
        A Bay Area native, Rivera grew up in Castro Valley and graduated from San Francisco State University with a degree in film production. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1629135545050-VOQWBTS3U3GODS5KJS1V/20130206DavidRyu04.jpg?format=1500w'} Pname={'DAVID RYU    '} job={'VICE PRESIDENT, SOFTWARE RESEARCH & DEVELOPMENT'}
        about={`David Ryu joined Pixar Animation Studios in 2001. After working as a graphics software engineer in Pixar’s tools department, David has since worked in a variety of capacities on multiple Academy Award®-winning feature films. He worked as a character shading artist on 2003’s "Finding Nemo," as a crowds technical director and on global technology for 2007’s "Ratatouille,” and as a crowds technical director for 2008’s "WALL•E." David also worked on global technology for the Academy Award®-winning feature "Up,” as shots sequence lead on "Toy Story 3,” and global technology supervisor on “Monsters University.” David supervised the effort to transition Pixar to a fully path-traced rendering environment on “Finding Dory.” David then served as supervising technical director for 2017’s Oscar®-winning feature film "Coco" and most recently held the role of visual effects supervisor on the 2021 release, “Luca.” 

        In 2021, Ryu was promoted to Vice President, Tools. In this role, he oversees the studio graphics and animation software including the Academy Award®-winning animation software “Presto.”
        
        Raised in Tustin, California, David was influenced by the "Star Wars" films and attended Harvard University, where he received his degree in 2001.  While in school, he interned at Electronic Arts and Microsoft, where he briefly worked on Microsoft Word and Tiger Woods golf video games.
        
        David currently resides in the San Francisco Bay Area with his family. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567096525250-5FDG8DJA9N7AQGSIQH5O/serafian.jpg?format=1500w'} Pname={'KATHERINE SARAFIAN'} job={'SENIOR VICE PRESIDENT, TALENT'}
        about={`Katherine Sarafian is the Senior Vice President, Talent, at Pixar Animation Studios.  In this capacity, she oversees the development and cultivation of Pixar’s workforce at all levels, helping shape the filmmaking experience at the studio.

        A Pixar veteran, Sarafian produced the Academy Award®-winning feature film Brave and the Academy Award®-nominated short film Lifted. She joined the studio in 1994 as a coordinator on Toy Story and held a variety of key production roles, including production supervisor on the Academy Award®-nominated Monsters, Inc. and production manager on the Academy Award®-winning The Incredibles, before beginning her tenure as a producer.
        
        Sarafian’s experience spans the range of Pixar’s creative and business interests; in addition to her film production work, she has overseen Pixar’s feature film development department and served as its Director of Marketing and Consumer Products. Prior to her promotion to Senior Vice President, Talent, she served as the studio’s Vice President, Strategic Talent Planning.
        
        Before joining Pixar, Sarafian worked in development at Castle Rock Entertainment and in digital entertainment at Sanctuary Woods Multimedia. 
        
        Sarafian received her BA in Communication Studies and MA in Film and Television Critical Studies from the University of California, Los Angeles. She is a member of the Academy of Motion Picture Arts and Sciences and the Producers Guild of America.`}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1568849378167-GA5CVZVAWGHSA7QFSI6D/dan2.jpg?format=1500w'} Pname={'DAN SCANLON'} job={'VICE PRESIDENT, CREATIVE'}
        about={`Dan Scanlon joined Pixar Animation Studios in September 2001 as a storyboard artist on Pixar’s award-winning feature films “Cars” and “Toy Story 3.” During the initial production stages for both films, he worked closely with the directors to bring their ideas to the screen.

        Scanlon went on to co-direct the original short film, “Mater and the Ghostlight,” which is included as one of the bonus features on the “Cars” DVD.  In addition to his work at Pixar, Scanlon simultaneously wrote and directed the live action film “Tracy,” released in 2009. 
        
        Scanlon made his animated feature directorial debut in 2013 with “Monsters University,” which grossed over $738.9 million worldwide at the box office, and received the 2013 “Hollywood Animation Award” from the Hollywood Film Awards. Scanlon most recently directed Pixar’s original feature film “Onward,” which released March 6, 2020.
        
        In his role as Vice President, Creative, Scanlon is involved in key creative decision-making at the studio and consults on films in both development and production. Scanlon served as Executive Producer on Pixar’s most recent film release “Soul,” and is also the Executive Producer on an upcoming unannounced Pixar film. 
        
        As a child growing up in Clawson, Michigan, Scanlon possessed a love for Warner Bros. cartoons, animated Disney films, and as fate would have it, Pixar short films. His passion inspired him to study film and animation in high school and in college, where he focused on illustration at Columbus College of Art and Design (CCAD). 
        
        Upon graduating from CCAD, Scanlon began working as an animator and story artist for Character Builders, a 2D animation company that produced feature and commercial work in Columbus, Ohio. 
        
        Scanlon currently resides in San Francisco with his wife Michele.  `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1620918716158-PPZVL8GWSNN1R1ITZ6M2/Schroeder.jpg?format=1500w'} Pname={'JESSIE SCHROEDER '} job={'VICE PRESIDENT, POST PRODUCTION'}
        about={`Jessie Schroeder began at Pixar Animation Studios in December 2016 as the post production supervisor on Cars 3. Since then, she worked as the post production producer for each Pixar feature, including the Academy Award®-winning films “Coco” and “Toy Story 4.” Schroeder is currently the vice president of post production, where she oversees the post production of all feature films and streaming content for the studio, as well as the teams that manage and operate Pixar’s mastering and creative film services.

        Prior to Pixar, Schroeder started her career working closely with the producing team for 1492 Pictures on “Bicentennial Man” and the first three “Harry Potter” films (from pre-production through principal photography and post production). In 2004, Warner Bros. approached Schroeder to oversee post production on all their films in the UK at the time, which included continued work on the “Harry Potter” series, “Batman Begins,” “Charlie and The Chocolate Factory” and “Frankenweenie.” From there, she began specializing as a post production supervisor on larger budget live action films with heavy VFX for Warner Bros., Walt Disney Studios, Sony Pictures and Twentieth Century Fox, working regularly with directors including Tim Burton and Alfonso Cuarón. Schroeder is also a member of both AMPAS and BAFTA. 
        
        Growing up in Mantoloking, NJ, Schroeder went to Point Pleasant Beach High School before attending Trinity College in Hartford, CT where she received her BA in English Literature. 
        
        Schroeder currently resides with her family in Corte Madera, CA. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/3ffe50f2-f76b-4190-aa81-b5ce8a064f2e/domee.jpg?format=1500w'} Pname={'DOMEE SHI'} job={'VICE PRESIDENT, CREATIVE'}
        about={`Domee Shi began as a story intern at Pixar Animation Studios in June 2011, and was soon hired as a story artist on the Academy Award®-winning feature film “Inside Out.” Since then, she has worked on the feature films “The Good Dinosaur,” “Incredibles 2” and the Academy Award®-winning “Toy Story 4.” In 2015 she began pitching ideas for short films, and soon was green lit to write and direct “Bao” which won the Academy Award® for Best Animated Short Film. In her role as a Creative VP, Shi is involved in key creative decision-making at the studio and consults on films in both development and production. Shi most recently made her feature film directorial debut on “Turning Red,” which released on Disney+ March 11, 2022.

        Shi graduated from the animation program at Sheridan College where she was fueled by her love of anime/manga, Disney, and Asian cinema influences that can be seen in her work to this day.
        
        Shi was born in Chongqing, China and resided in Toronto, Canada most of her life. She currently lives in Oakland, California and notes that her love of animation is only rivaled by her love of cats.`}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1599752052647-FN5HMGQCQWWRDI6AJ5M2/20141007PeterSohn10.JPG?format=1500w'} Pname={'PETER SOHN'} job={'VICE PRESIDENT, CREATIVE'}
        about={`Peter Sohn joined Pixar Animation Studios in September 2000, and began working in both the art and story departments for the Academy Award®-winning “Finding Nemo.”  Sohn continued on to work on “The Incredibles” in the art, story, and animation departments.  He focused on animating members of the Parr family and worked on many memorable scenes from the film. He also worked as a story artist on another Oscar® winner, the 2008 feature film, “WALL•E.” 

        Sohn worked with producer Kevin Reher on the Pixar short “Partly Cloudy,” which was also his directorial debut at Pixar. Sohn directed Disney•Pixar’s original feature “The Good Dinosaur,” which opened in theaters in 2015.
       
        In addition to his contributions as a filmmaker, Sohn has lent his voice talents to Pixar’s feature films.  In “Ratatouille” he voiced the character of Emile, and in “Monsters University,” he is the voice of Scott “Squishy” Squibbles. 
       
        Prior to Pixar, Sohn worked at Warner Bros. with “Ratatouille” director Brad Bird on “The Iron Giant,” as well as at Disney TV.  He grew up in New York and attended California Institute of the Arts (Cal Arts).  He currently lives in the Bay Area. `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567630431638-09XCYDOVLS3YJFSIWZH0/stanton3.jpg?format=1500w'} Pname={'ANDREW STANTON'} job={'VICE PRESIDENT, CREATIVE'}
        about={`Andrew Stanton has been a major creative force at Pixar Animation Studios since 1990, when he became the second animator and ninth employee to join the company’s elite group of computer animation pioneers.  As Vice President, Creative he currently oversees all shorts and feature projects at the studio.  Stanton wrote and directed the Academy Award®-winning Disney and Pixar feature film “WALL•E,” for which he also received a Best Original Screenplay Oscar®-nomination.  In 2016 Stanton directed Disney and Pixar’s “Finding Dory,” which, upon release, became the highest-grossing domestic animated feature of all time and in 2019 Stanton served as screenwriter and executive producer of “Toy Story 4.”

        Stanton made his directorial debut with the record-shattering “Finding Nemo,” an original story of his that he also co-wrote.  The film garnered Stanton two Academy Award® nominations (Best Original Screenplay and Best Animated Film), and “Finding Nemo” was awarded an Oscar® for Best Animated Feature Film of 2003, the first such honor Pixar Animation Studios received for a full-length feature film. 
        
        One of the four screenwriters to receive an Oscar® nomination in 1996 for his contribution to “Toy Story,” Stanton went on to receive credit as a screenwriter on every subsequent Pixar film – “A Bug’s Life,” “Toy Story 2,” “Monsters, Inc.” and “Finding Nemo.”  Additionally, he served as co-director on “A Bug’s Life,” and was the executive producer of “Monsters, Inc.,” and “Monsters University,” and Academy Award®-winning films “Ratatouille” and “Brave.” 
        
        In addition to his multi-award winning animation work, Stanton made his live-action writing and directorial debut with Disney’s “John Carter,” released in March 2012. 
        
        A native of Rockport, Massachusetts, Stanton earned a Bachelor of Fine Arts in Character Animation from California Institute of the Arts (Cal Arts), where he completed two student films.  In the 1980s, he launched his professional career in Los Angeles animating for Bill Kroyer’s Kroyer Films studio, and writing for Ralph Bakshi’s production of “Mighty Mouse, The New Adventures” (1987).  `}/> <br /> <br /> <br /> 
<br />          <About_P img={'https://images.squarespace-cdn.com/content/v1/51cdafc4e4b09eb676a64e68/1567101246782-YC8RXXLK4EWJ38EZPL6H/weinberg.jpg?format=1500w'} Pname={'JODY WEINBERG'} job={'VICE PRESIDENT, BUSINESS AFFAIRS & LEGAL COUNSEL'}
        about={`Jody Weinberg starting working for Pixar Animation Studios in June 1995 in connection with “Toy Story” as Director, Business and Legal Affairs for Walt Disney Feature Animation, and continued to work on all Pixar features through July 2001. Weinberg became an independent contractor for Pixar in July 2003, and remained in that capacity until she joined the studio fulltime in September 2006 as Associate General Counsel. As of July 2019, Weinberg was promoted to Vice President, Business Affairs & Legal Counsel at Pixar. 

        As the Vice President Business Affairs & Legal Counsel, Weinberg handles structuring, negotiating, and documenting business and legal terms for the engagement of outside voice, writing, and other talent in Pixar productions; and providing legal counsel and services in all aspects of production, with a focus on intellectual property matters. 
        
        Prior to Pixar, Weinberg worked as a contract lawyer in Century City, CA; was a Marshall’s Office intern at the Supreme Court of the United States; a legal intern at MCA TV / Universal; a legal intern at Public Counsel working on FEMA and SBA appeals for victims of the Rodney King riots; a legal intern at Santa Monica City Attorney’s Office, Criminal Division; and an intern for the Fresno County Board of Supervisors. 
        
        Weinberg grew up in Fresno, CA and attended San Joaquin Memorial High School. She received her B.A. in both English and Political Science at the University of Michigan, and her J.D. from the Pepperdine University School of Law. Weinberg currently resides in Encino, CA. `}/> <br /> <br /> <br /> 
<br />     </ div>
    )
}
